version: 2.1

orbs:
  haskell: haskell-works/haskell-build@4.1.7
  github: haskell-works/github-release@1.3.3
  hackage: haskell-works/hackage@1.4.2
  merge-point: haskell-works/merge-point@1.0.0

executors:
  cabal-build:
    parameters:
      ghc-version:
        description: GHC Version
        type: string
    docker:
      - image: quay.io/haskell_works/ghc-<< parameters.ghc-version >>
      - image: confluentinc/cp-zookeeper:5.1.0
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181

      - image: confluentinc/cp-kafka:5.1.0
        environment:
          KAFKA_ZOOKEEPER_CONNECT: "localhost:2181"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

commands:
  build-librdkafka:
    description: Build librdkafka
    steps:
      - restore_cache:
          key: cache--{{ .Environment.CACHE_VERSION }}--librdkafka--{{ checksum "scripts/build-librdkafka" }}
      - run:
          name: Build librdkafka
          command: ./scripts/build-librdkafka
      - save_cache:
          key: cache--{{ .Environment.CACHE_VERSION }}--librdkafka--{{ checksum "scripts/build-librdkafka" }}
          paths: .librdkafka

workflows:
  build-app-pipelines:
    jobs:
      - haskell/build-with-binary-cache:
          name: GHC 8.4.4
          executor:
            name: cabal-build
            ghc-version: 8.4.4
          before-build: [build-librdkafka]
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --flag it --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.6.5
          executor:
            name: cabal-build
            ghc-version: 8.6.5
          before-build: [build-librdkafka]
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --flag it --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.8.3
          executor:
            name: cabal-build
            ghc-version: 8.8.3
          before-build: [build-librdkafka]
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --flag it --test-options='+RTS -g1'

      - haskell/build-with-binary-cache:
          name: GHC 8.10.1
          executor:
            name: cabal-build
            ghc-version: 8.10.1
          before-build: [build-librdkafka]
          context: haskell-ci
          binary-cache-uri: ${BINARY_CACHE_URI-"http://hw-binary-cache-us-west-2-a.s3-website-us-west-2.amazonaws.com/archive"}
          cabal-build-extra: --write-ghc-environment-files=ghc8.4.4+
          cabal-test-extra: --test-show-details=direct --flag it --test-options='+RTS -g1'

      - merge-point/merge-point:
          name: Build Ok
          requires:
            - GHC 8.4.4
            - GHC 8.6.5
            - GHC 8.8.3
            - GHC 8.10.1

      - github/release-cabal:
          name: GitHub Release
          context: haskell-ci
          requires:
            - Build Ok
          checkout: true
          filters:
            branches:
              only: master

      - hackage/upload:
          publish: true
          requires:
            - GitHub Release
          username: ${HACKAGE_USER}
          password: ${HACKAGE_PASS}
          filters:
            branches:
              only: master
